services:
  db:
    container_name: timer_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: timer
    volumes:
      - timer_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    networks:
      - timer_network

  adminer:
    container_name: timer_adminer
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: dracula
    networks:
      - timer_network

  back:
    container_name: timer_back
    build:
      context: ./back
      dockerfile: Dockerfile 
    ports:
      - "4000:8000"
    environment:
      IS_DOCKER: true
      POSTGRES_URL: ${POSTGRES_URL}
    networks:
      - timer_network

volumes:
  timer_data:

networks:
  timer_network: