"""Added seed status

Revision ID: 45bd9f12fbf8
Revises: d8220df288b8
Create Date: 2024-10-06 16:45:51.595928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45bd9f12fbf8'
down_revision: Union[str, None] = 'd8220df288b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeding',
        sa.Column('done', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('done')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeding')
    # ### end Alembic commands ###
