"""Improved Models

Revision ID: d8220df288b8
Revises: 22c288f58bcf
Create Date: 2024-10-05 16:48:52.877635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8220df288b8'
down_revision: Union[str, None] = '22c288f58bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=False),
        sa.Column('start_zone', sa.String(), nullable=False),
        sa.Column('end_zone', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('unique_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time', sa.Float(), nullable=False),
        sa.Column('max_speed', sa.Float(), nullable=False),
        sa.Column('average_speed', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('map_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
        sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('times')
    op.drop_table('players')
    op.drop_table('maps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
        sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('maps_id_seq'::regclass)"), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('start_zone', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('end_zone', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='maps_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('players',
        sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('players_id_seq'::regclass)"), autoincrement=True, nullable=False),
        sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('unique_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='players_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('times',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('max_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('average_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('map_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name='times_map_id_fkey'),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='times_player_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='times_pkey')
    )
    op.drop_table('time')
    op.drop_table('player')
    op.drop_table('map')
    # ### end Alembic commands ###
